### ISSUE TITLE
In month view, don't show days which aren't in month

### ISSUE THREAD

**Issue by yringler** [schedule-x/schedule-x#661]
**Is your feature request related to a problem? Please describe.**  
Our design requires that, in month view, days which aren't in month aren't visible. There should be a way to configure that.

**Describe the solution you'd like**  
An option could be added to month view if to show non current dates

**Additional context**  

**Things that could speed up the process**
- [ ] I can picture implementing at least parts of this feature
- [ ] I believe I know how to do this, and am willing to implement the whole thing.

**Comment by tomosterlund** [comment]
Actually I realized you can already achieve this with a CSS override like so for month-agenda

```css
.sx__month-agenda-day.is-leading-or-trailing {
  opacity: 0;
  pointer-events: none;
}
```

does that solve your problem?
