### ISSUE TITLE
CSS Variable --sx-color-neutral-variant Not Applied to Icons in Light Theme for @schedule-x/event-modal

### ISSUE THREAD

**Issue by t-lecoublet** [schedule-x/schedule-x#841]
**Context:**

- Library version: `@schedule-x/vue` (2.11.1) and `@schedule-x/event-modal` (2.12.1)
- Browser: Firefox Developer 134.0b10

**Description**:  
I am using the `@schedule-x/vue` library, specifically the `@schedule-x/event-modal` module. I have encountered an issue regarding the customization of icon colors using CSS variables as documented.  

Here are the CSS variables I am using in my project:  
```css
:root {
    --sx-color-primary: var(--fallback-p,oklch(var(--p)/var(--tw-bg-opacity, 1)));
    --sx-color-surface-dim: var(--fallback-s,oklch(var(--s)/var(--tw-bg-opacity, 1)));
    --sx-color-background: var(--fallback-b1,oklch(var(--b1)/var(--tw-bg-opacity, 1)));
    --sx-internal-color-text: var(--fallback-bc,oklch(var(--bc)/var(--tw-text-opacity, 1)));
    --sx-color-on-background: var(--fallback-bc,oklch(var(--bc)/var(--tw-text-opacity, 1)));
    --sx-internal-color-light-gray: var(--fallback-b3,oklch(var(--b3)/var(--tw-bg-opacity, 1)));
    --sx-color-neutral-variant: var(--fallback-bc,oklch(var(--bc)/var(--tw-text-opacity, 1)));
}
```
The CSS variables used above are applied dynamically and work well, except for the last one, --sx-color-neutral-variant.

The issue arises when trying to customize the icon colors in the modal. The variable `--sx-color-neutral-variant` is only applied to icons when the dark theme is enabled (`isDark: true`)  in the `createCalendar()` configuration. In the light theme, this variable is not used, and the icon colors default to `#000`, as indicated by the code in `@schedule-x/event-modal/dist/core.umd.js` at line 169:  
```javascript
const useIconColors = ($app) => {
    const ICON_COLOR_LIGHT_MODE = '#000';
    const ICON_COLOR_DARK_MODE = 'var(--sx-color-neutral-variant)';
    const iconColor = signals.signal($app.calendarState.isDark.value
        ? ICON_COLOR_DARK_MODE
        : ICON_COLOR_LIGHT_MODE);
    signals.effect(() => {
        if ($app.calendarState.isDark.value)
            iconColor.value = ICON_COLOR_DARK_MODE;
        else
            iconColor.value = ICON_COLOR_LIGHT_MODE;
    });
    return iconColor;
};
```

**To Reproduce**

1. Use `@schedule-x/vue` and `@schedule-x/event-modal` in your project.  
2. Define the `--sx-color-neutral-variant` variable in your CSS.  
3. Set the component to light theme.  
4. Observe that the `--sx-color-neutral-variant` variable is not applied to the icons, and they default to black (`#000`).

**Expected behavior**

I would expect the `--sx-color-neutral-variant` variable to be used for icon colors in both light and dark themes, allowing for consistent and dynamic theming via CSS variables.

**Observed Behavior**:  
In the light theme, the icons do not use the `--sx-color-neutral-variant` variable and instead fall back to the hardcoded value `#000`.

**Questions**:  
1. Is this behavior intentional, and if so, what is the reasoning behind it?  
2. Are there any workarounds or alternatives to dynamically style icons via CSS without forcing the dark theme?
